# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'M-Tribes Challenge' do
   
   pod 'Alamofire', '~> 4.5'
   pod 'SwiftyJSON'
  target 'M-Tribes ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'M-Tribes ChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
